In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.python.framework import ops
ops.reset_default_graph()
tf.compat.v1.disable_eager_execution()
sess = tf.compat.v1.Session()

/home/ma-user/anaconda3/envs/TensorFlow-2.1.0/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
identiy_matrix = tf.compat.v1.diag([1.0, 1.0, 1.0])
print(sess.run(identiy_matrix))
A = tf.compat.v1.truncated_normal([2,3])
print(sess.run(A))
B = tf.fill([2,3],5.0)
print(sess.run(B))
C = tf.compat.v1.random_uniform([3,2])
print(sess.run(C))
D = tf.compat.v1.convert_to_tensor(np.array([[1.,2.,3.],[-3.,-7.,-1.],[0.,5.,-2.]]))
print(sess.run(D))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 0.28321186  0.55567586  1.1733472 ]
 [-1.7252342  -0.12275252  1.0689898 ]]
[[5. 5. 5.]
 [5. 5. 5.]]
[[0.2804953  0.8541951 ]
 [0.80523515 0.53468   ]
 [0.11972344 0.9267837 ]]
[[ 1.  2.  3.]
 [-3. -7. -1.]
 [ 0.  5. -2.]]


In [3]:
E = tf.zeros([2,3,3])
print(sess.run(E))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [4]:
print(sess.run(A+B))
print(sess.run(B-B))

[[5.5578065 4.384751  5.262491 ]
 [3.542943  6.457121  4.032861 ]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
print(sess.run(tf.matmul(B, identiy_matrix)))

[[5. 5. 5.]
 [5. 5. 5.]]


In [6]:
try:
    print(sess.run(tf.matmul(A, B)))
except:
    print("ValueError: Dimensions must be equal")

ValueError: Dimensions must be equal


In [7]:
help(tf.matmul);

Help on function matmul in module tensorflow.python.ops.math_ops:

matmul(a, b, transpose_a=False, transpose_b=False, adjoint_a=False, adjoint_b=False, a_is_sparse=False, b_is_sparse=False, name=None)
    Multiplies matrix `a` by matrix `b`, producing `a` * `b`.
    
    The inputs must, following any transpositions, be tensors of rank >= 2
    where the inner 2 dimensions specify valid matrix multiplication dimensions,
    and any further outer dimensions specify matching batch size.
    
    Both matrices must be of the same type. The supported types are:
    `float16`, `float32`, `float64`, `int32`, `complex64`, `complex128`.
    
    Either matrix can be transposed or adjointed (conjugated and transposed) on
    the fly by setting one of the corresponding flag to `True`. These are `False`
    by default.
    
    If one or both of the matrices contain a lot of zeros, a more efficient
    multiplication algorithm can be used by setting the corresponding
    `a_is_sparse` or `b_is_sp

In [8]:
print(sess.run(tf.transpose(C)))

[[0.33106422 0.76668906 0.54454565]
 [0.2699653  0.35497868 0.5479125 ]]


In [9]:
print(sess.run(tf.compat.v1.matrix_determinant(D)))

-37.99999999999999


In [10]:
print(sess.run(tf.compat.v1.matrix_inverse(D)))

[[-0.5        -0.5        -0.5       ]
 [ 0.15789474  0.05263158  0.21052632]
 [ 0.39473684  0.13157895  0.02631579]]


In [11]:
print(sess.run(tf.compat.v1.self_adjoint_eig(D)[0]))

[-10.65907521  -0.22750691   2.88658212]


In [12]:
print(sess.run(tf.compat.v1.self_adjoint_eig(D)[1]))

[[ 0.21749542  0.63250104 -0.74339638]
 [ 0.84526515  0.2587998   0.46749277]
 [-0.4880805   0.73004459  0.47834331]]


In [17]:
print(sess.run(tf.compat.v1.cholesky(identiy_matrix)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
eigenvalues, eigenvectors = sess.run(tf.compat.v1.self_adjoint_eig(D))

In [19]:
eigenvalues

array([-10.65907521,  -0.22750691,   2.88658212])

In [20]:
eigenvectors

array([[ 0.21749542,  0.63250104, -0.74339638],
       [ 0.84526515,  0.2587998 ,  0.46749277],
       [-0.4880805 ,  0.73004459,  0.47834331]])